name: Revanced APKs

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    paths:
      - ".github/workflows/blank.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Revanced Youtube
        run: sh revanced youtube

        #- name: Run Revanced Youtube Music
        #run: sh revanced youtube-music

      - name: Check for APK files
        id: check_apks
        run: |
          if ls *.apk 1> /dev/null 2>&1; then 
            echo "apks_exist=true" >> "$GITHUB_ENV"
            RELEASE_TAG="$(date +'%Y-%m-%d')" 
            echo "RELEASE_TAG=$RELEASE_TAG" >> "$GITHUB_ENV"
          else
            echo "apks_exist=false" >> "$GITHUB_ENV"
          fi

      - name: Upload binaries to release
        if: env.apks_exist == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: yt-*.apk
          tag: ${{ env.RELEASE_TAG }}
          overwrite: true
          file_glob: true
          body: "New Releases."

      - name: auto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: New Version"
          repository: .
          file_pattern: track
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
