name: Revanced APKs

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    paths:
      - ".github/workflows/blank.yml"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Revanced Youtube
        run: sh revanced youtube

      - name: Run Revanced Youtube Music
        run: sh revanced youtube-music 7.29.52

      - name: Check for APK files
        id: check_apks
        run: |
          if ls *.apk 1> /dev/null 2>&1; then 
            echo "apks_exist=true" >> $GITHUB_OUTPUT
            echo "release_tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          else
            echo "apks_exist=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Set NOW
        id: now
        run: |
          echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload binaries to release
        #if: steps.check_apks.outputs.apks_exist == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /home/runner/yt-*.apk
          tag: ${{ steps.now.outputs.NOW }}
          overwrite: true
          file_glob: true
          body: "New Releases."

      - name: auto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: New Version"
          repository: .
          file_pattern: track
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

