name: Revanced APKs

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    paths:
      - ".github/workflows/blank.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Revanced Youtube
        run: sh revanced youtube

      - name: Run Revanced Youtube Music
        run: sh revanced youtube-music 6.45.54

      - name: Upload binaries to release
        if: steps.check_apks.outputs.apks_exist == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /home/runner/yt-*.apk
          tag: latest
          overwrite: true
          file_glob: true
          body: "New Releases."

      - name: auto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: New Version"
          repository: .
          file_pattern: track
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

