name: Revanced APKs

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    paths:
      - ".github/workflows/blank.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Revanced Youtube
        run: sh revanced youtube

      - name: Run Revanced Youtube Music
        run: sh revanced youtube-music

      - name: Check for APK files
        id: check_apks
        run: |
          if ls *.apk 1> /dev/null 2>&1; then 
            echo "apks_exist=true" >> $GITHUB_OUTPUT
            echo "RELEASE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          else
            echo "apks_exist=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: set apk for upload
        run: |
             sudo apt install zip unzip -y
             mkdir yt-revanced
             mv *.apk yt-revanced
             zip -r yt-revanced.zip yt-revanced

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: yt-revanced.zip
          tag: latest
          overwrite: true
          file_glob: true
          body: "New Releases."

      - name: auto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: New Version"
          repository: .
          file_pattern: track
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
